package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class qwe implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public qwe() {
    }




}